service: attendance-tracker-serverless-v3
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  profile: ServerlessUserBasic
  stage: dev
  environment:
    usersTable: ${self:custom.usersTable}
    coursesTable: ${self:custom.coursesTable}
    tempLoginTable: ${self:custom.tempLoginTable}
    attendanceTable: ${self:custom.attendanceTable}
  ##TODO: grant fine grained permissions per lambda
  iam: #TODO: reduce these to principle of least privilege
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.usersTable}
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.tempLoginTable}
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            # TODO: grant permissions on the necessary index?
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.attendanceTable}

functions:
  loginUser:
    handler: handlers/loginUser/loginUser.handler
    events:
      - http:
          path: /login
          cors: true
          method: post
  registerUser:
    handler: handlers/registerUser/registerUser.handler
    events:
      - http:
          path: /register
          cors: true
          method: post
  student-addAttendance:
    handler: handlers/student-addAttendance/addAttendance.handler
    events:
      - http:
          path: /addAttendance
          cors: true
          method: post
  teacher-verifyAttendance:
    handler: handlers/teacher-verifyAttendance/verifyAttendance.handler
    events:
      - http:
          path: /verifyAttendance
          cors: true
          method: post

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  frontendBucketName: attendance-tracker-bucket-19054
  s3Sync:
    - bucketName: ${self:custom.frontendBucketName}
      localDir: attendance-tracker-frontend/build/
  usersTable: attendance-tracker-users
  coursesTable: attendance-tracker-courses
  attendanceTable: attendance-tracker-student-attendances
  tempLoginTable: attendance-tracker-users-temp-login #TODO: add hashing, phase this into a Cognito user pool

resources:
  Resources:
    AttendanceTrackerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.frontendBucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AttendanceTrackerBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.frontendBucketName}/*
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.frontendBucketName}.s3.amazonaws.com
              Id: AttendanceTrackerApp
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: "true"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: AttendanceTrackerApp
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AttendanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.attendanceTable}
        AttributeDefinitions:
          - AttributeName: ID #TODO: make the primary key a combo of ID/email, course section, and Date rows (YYYY-MM-DD format) [three strings in table]
            AttributeType: S
        KeySchema:
          - AttributeName: ID #email|section|date format
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.coursesTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    TempLoginTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tempLoginTable}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-user-pool
        UsernameAttributes: #TODO: figure out how to have multiple accounts in dev mode without needing to provision emails
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-user-pool-client
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
        UserPoolId:
          Ref: CognitoUserPool
